language: Java
before_install:
 - chmod +x gradlew
jobs:
  include:
    - stage: build
      script: ./gradlew build
    - stage: generatePomFile
      script: ./gradlew generatePomFileForBintrayPublicationPublication
    - stage: deploy
      script: ./gradlew -Pbintray-user=${bintray_user} -Pbintray-key=${bintray_key} bintrayUpload -x clean